---
title: "git_00"
author: "Aubrey Garcia"
date: "O5/27/2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with a sequence of commits to the master branch.
Our project will be done using several commits to the master branch.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
`Twas brillig, and the slithy toves


 Did gyre and gimble in the wabe:
 
 
All mimsy were the borogoves,


 And the mome raths outgrabe.
 
 
"Beware the Jabberwock, my son!


 The jaws that bite, the claws that catch!
 
 


## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

I went to turn the grass once after one


Who mowed it in the dew before the sun.


The dew was gone that made his blade so keen


Before I came to view the levelled scene.


I looked for him behind an isle of trees;


I listened for his whetstone on the breeze.


## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->


The sun was shining on the sea,
   Shining with all his might
   
   
He did his very best to make
   The billows smooth and bright—


## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->

A thing of beauty is a joy for ever:


Its loveliness increases; it will never


Pass into nothingness; but still will keep


A bower quiet for us, and a sleep


Full of sweet dreams, and health, and quiet breathing.


– John Keats (1)
